In [1]:
import pandas as pd
import glob

In [2]:
files = glob.glob('*.xlsx')
final_df = pd.DataFrame()
for file in files:
    df = pd.read_excel(file)
    final_df = pd.concat([df,final_df])
final_df = final_df.drop('Unnamed: 0',axis=1)
final_df = final_df.dropna(subset=['text'])
print(final_df)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\$honeybakesin_instagram.xlsx'

In [3]:
final_df.columns

Index(['id', '__typename', 'shortcode', 'comments_disabled',
       'taken_at_timestamp', 'dimensions', 'display_url', 'thumbnail_src',
       'thumbnail_resources', 'is_video', 'video_view_count', 'caption',
       'Number_of_comments', 'Number_of_likes', 'owner_id',
       'commenter_post_id', 'text', 'created_at', 'owner', 'commentor_id',
       'commentor_profile_pic', 'username', 'id_x', 'id_y',
       'username_commentor'],
      dtype='object')

In [37]:
final_df.to_excel('insta_overall_master.xlsx')

In [32]:
pro = final_df.dropna(subset = ['text'])

In [33]:
pro.columns

Index(['id', '__typename', 'shortcode', 'comments_disabled',
       'taken_at_timestamp', 'dimensions', 'display_url', 'thumbnail_src',
       'thumbnail_resources', 'is_video', 'video_view_count', 'caption',
       'Number_of_comments', 'Number_of_likes', 'owner_id',
       'commenter_post_id', 'text', 'created_at', 'owner', 'commentor_id',
       'commentor_profile_pic', 'username', 'id_x', 'id_y',
       'username_commentor'],
      dtype='object')

In [35]:
final_df = final_df[['shortcode','caption','Number_of_comments','Number_of_likes','text','username','username_commentor']]

In [36]:
final_df

,shortcode,caption,Number_of_comments,Number_of_likes,text,username,username_commentor
0,B0nROchHqIs,Everything that your pet needs is now availabl...,1,1218,#petcare #dogsofinstagram #doglovers #happy #p...,sanchu_animalhospital,NaN
1,B05jMzgHoZ0,The way you pet a dog can determine how they m...,1,27,#dogsofchennai #chennaidogs #therapydogs #touc...,sanchu_animalhospital,NaN
6,B5KIVpbnDtg,"An offer you wouldn’t want to miss, neither wi...",1,846,Nice,balaji_balajikumar,NaN
12,B6FyPLUn3DS,We have all heard stories about cats and their...,1,16,The cat will always be sleeping mode,beatu18121988,NaN
13,B6SNkllHCMI,Look at these cuties cuddled up. They came in ...,1,39,Thank you @sanchu_animalhospital for deworming...,daisylou_chillidog_chloeblu,NaN
...,...,...,...,...,...,...,...
235,CNSN-BbDFAj,Choco Floral Cake 💕 \n\n.\n.\n.\n.\n.\n.\n#cho...,4,71,Price,NaN,_shop_from_home
236,CNSN-BbDFAj,Choco Floral Cake 💕 \n\n.\n.\n.\n.\n.\n.\n#cho...,4,71,😍,NaN,dheerchiya_27
237,CNSN-BbDFAj,Choco Floral Cake 💕 \n\n.\n.\n.\n.\n.\n.\n#cho...,4,71,Price?,NaN,pplcallme_sush_
238,CNhqhtTjD-m,A beautiful princess cake in the flavor of Man...,1,84,Pp,NaN,mamma_andher_muse
239,CNr_1Kjj6Rm,"And FINALLY, it’s Mango Season 🥭 \n\nHow many ...",1,41,Pp for one kg sis,NaN,mohanatms1307

In [3]:
pro = final_df[['shortcode','text']]

In [8]:
pro = pro.dropna(subset = ['text'])

In [9]:
pro

       shortcode                                               text
0    B0nROchHqIs  petcare dogsofinstagram doglovers happy pet go...
1    B05jMzgHoZ0  dogsofchennai chennaidogs therapydogs touchmen...
6    B5KIVpbnDtg                                               Nice
12   B6FyPLUn3DS               The cat will always be sleeping mode
13   B6SNkllHCMI  Thank you sanchuanimalhospital for deworming t...
..           ...                                                ...
235  CNSN-BbDFAj                                              Price
236  CNSN-BbDFAj                                                  😍
237  CNSN-BbDFAj                                              Price
238  CNhqhtTjD-m                                                 Pp
239  CNr_1Kjj6Rm                                  Pp for one kg sis

[25147 rows x 2 columns]

In [44]:
import re
pro['text'] = pro['text'].apply(lambda x:re.sub(r"[@#$%^""&*’(_.)-+=!?/|\\',;:]", '',x) if x==x else x)
pro['text'] = pro['text'].apply(lambda x:re.sub(r"[“’”]", '',x))
pro['text'] = pro['text'].apply(lambda x:re.sub(" \d+", "", x))

In [45]:
pro['text']

0      petcare dogsofinstagram doglovers happy pet go...
1      dogsofchennai chennaidogs therapydogs touchmen...
6                                                   Nice
12                  The cat will always be sleeping mode
13     Thank you sanchuanimalhospital for deworming t...
                             ...
235                                                Price
236                                                    😍
237                                                Price
238                                                   Pp
239                                    Pp for one kg sis
Name: text, Length: 5078, dtype: object

In [46]:
import nltk
import swifter
from rake_nltk import Rake
nltk.download('stopwords')
nltk.download('punkt')
r = Rake()

def rakeprocessing(text):
    r.extract_keywords_from_text(text)
    return r.get_ranked_phrases_with_scores()

[nltk_data] Downloading package stopwords to C:\Users\HEPL-
[nltk_data]     IT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\HEPL-
[nltk_data]     IT\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [47]:
pro['Rake'] = pro.text.apply(lambda x:rakeprocessing(x))

In [48]:
pro['Rake']

0      [(900.0, petcare dogsofinstagram doglovers hap...
1      [(49.0, dogsofchennai chennaidogs therapydogs ...
6                                          [(1.0, nice)]
12     [(4.0, sleeping mode), (1.0, cat), (1.0, always)]
13     [(9.0, thorough examination 😊), (4.0, please c...
                             ...
235                                       [(1.0, price)]
236                                           [(1.0, 😍)]
237                                       [(1.0, price)]
238                                          [(1.0, pp)]
239                       [(9.0, one kg sis), (1.0, pp)]
Name: Rake, Length: 5078, dtype: object

In [49]:
rke = pro.explode('Rake')
print(rke)
rke=rke.dropna(subset=['Rake'])
rke['Rake_text'] = rke.Rake.apply(lambda x:x[1])
rke['Rake_Score'] = rke.Rake.apply(lambda x:str(int(x[0])))

       shortcode                                               text  \
0    B0nROchHqIs  petcare dogsofinstagram doglovers happy pet go...
1    B05jMzgHoZ0  dogsofchennai chennaidogs therapydogs touchmen...
6    B5KIVpbnDtg                                               Nice
12   B6FyPLUn3DS               The cat will always be sleeping mode
12   B6FyPLUn3DS               The cat will always be sleeping mode
..           ...                                                ...
236  CNSN-BbDFAj                                                  😍
237  CNSN-BbDFAj                                              Price
238  CNhqhtTjD-m                                                 Pp
239  CNr_1Kjj6Rm                                  Pp for one kg sis
239  CNr_1Kjj6Rm                                  Pp for one kg sis

                                                  Rake
0    (900.0, petcare dogsofinstagram doglovers happ...
1    (49.0, dogsofchennai chennaidogs therapydogs t...
6                                          (1.0, nice)
12                                (4.0, sleeping mode)
12                                          (1.0, cat)
..                                                 ...
236                                           (1.0, 😍)
237                                       (1.0, price)
238                                          (1.0, pp)
239                                  (9.0, one kg sis)
239                                          (1.0, pp)

[7153 rows x 3 columns]

In [50]:
rke = rke[rke['Rake_Score'].isin(['1','2','3','4'])]

In [51]:
rke = rke.drop(['Rake'],axis=1)

In [52]:
rke

,shortcode,text,Rake_text,Rake_Score
6,B5KIVpbnDtg,Nice,nice,1
12,B6FyPLUn3DS,The cat will always be sleeping mode,sleeping mode,4
12,B6FyPLUn3DS,The cat will always be sleeping mode,cat,1
12,B6FyPLUn3DS,The cat will always be sleeping mode,always,1
13,B6SNkllHCMI,Thank you sanchuanimalhospital for deworming t...,please contact,4
...,...,...,...,...
235,CNSN-BbDFAj,Price,price,1
236,CNSN-BbDFAj,😍,😍,1
237,CNSN-BbDFAj,Price,price,1
238,CNhqhtTjD-m,Pp,pp,1
239,CNr_1Kjj6Rm,Pp for one kg sis,pp,1

In [53]:
rke['image_url'] = ['https://www.instagram.com/p/{}/media/?size=l'.format(x) for x in rke['shortcode']]

0    https://www.instagram.com/p/CCaPer6nqaF/media/...
0    https://www.instagram.com/p/CCaPer6nqaF/media/...
0    https://www.instagram.com/p/CCaPer6nqaF/media/...
0    https://www.instagram.com/p/CI-oS3Mh2aF/media/...
Name: image_url, dtype: object

In [57]:
rke

,shortcode,text,Rake_text,Rake_Score,image_url
6,B5KIVpbnDtg,Nice,nice,1,https://www.instagram.com/p/B5KIVpbnDtg/media/...
12,B6FyPLUn3DS,The cat will always be sleeping mode,sleeping mode,4,https://www.instagram.com/p/B6FyPLUn3DS/media/...
12,B6FyPLUn3DS,The cat will always be sleeping mode,cat,1,https://www.instagram.com/p/B6FyPLUn3DS/media/...
12,B6FyPLUn3DS,The cat will always be sleeping mode,always,1,https://www.instagram.com/p/B6FyPLUn3DS/media/...
13,B6SNkllHCMI,Thank you sanchuanimalhospital for deworming t...,please contact,4,https://www.instagram.com/p/B6SNkllHCMI/media/...
...,...,...,...,...,...
235,CNSN-BbDFAj,Price,price,1,https://www.instagram.com/p/CNSN-BbDFAj/media/...
236,CNSN-BbDFAj,😍,😍,1,https://www.instagram.com/p/CNSN-BbDFAj/media/...
237,CNSN-BbDFAj,Price,price,1,https://www.instagram.com/p/CNSN-BbDFAj/media/...
238,CNhqhtTjD-m,Pp,pp,1,https://www.instagram.com/p/CNhqhtTjD-m/media/...
239,CNr_1Kjj6Rm,Pp for one kg sis,pp,1,https://www.instagram.com/p/CNr_1Kjj6Rm/media/...

In [58]:
rke.to_excel("Rake.xlsx")

In [7]:
pro

       shortcode                                               text
0    B0nROchHqIs  petcare dogsofinstagram doglovers happy pet go...
1    B05jMzgHoZ0  dogsofchennai chennaidogs therapydogs touchmen...
2    B0-txONHdg_                                                NaN
3    B1EBUtrHPXH                                                NaN
4    B1oRivEn2cI                                                NaN
..           ...                                                ...
235  CNSN-BbDFAj                                              Price
236  CNSN-BbDFAj                                                  😍
237  CNSN-BbDFAj                                              Price
238  CNhqhtTjD-m                                                 Pp
239  CNr_1Kjj6Rm                                  Pp for one kg sis

[25442 rows x 2 columns]

In [11]:
pro = final_df[['shortcode','text']]
pro = pro.dropna(subset = ['text'])
import re
pro['text'] = pro['text'].apply(lambda x:re.sub(r"[@#$%^""&*’(_.)-+=!?/|\\',;:]", '',x) if x==x else x)
pro['text'] = pro['text'].apply(lambda x:re.sub(r"[“’”]", '',x))
pro['text'] = pro['text'].apply(lambda x:re.sub(" \d+", "", x))

In [12]:
pro

       shortcode                                               text
0    B0nROchHqIs  petcare dogsofinstagram doglovers happy pet go...
1    B05jMzgHoZ0  dogsofchennai chennaidogs therapydogs touchmen...
6    B5KIVpbnDtg                                               Nice
12   B6FyPLUn3DS               The cat will always be sleeping mode
13   B6SNkllHCMI  Thank you sanchuanimalhospital for deworming t...
..           ...                                                ...
235  CNSN-BbDFAj                                              Price
236  CNSN-BbDFAj                                                  😍
237  CNSN-BbDFAj                                              Price
238  CNhqhtTjD-m                                                 Pp
239  CNr_1Kjj6Rm                                  Pp for one kg sis

[25147 rows x 2 columns]

In [66]:
emo = pro.copy()

In [68]:
emo = emo.dropna()
import emojis
emo['Emojis'] = emo['text'].apply(lambda x: list(emojis.get(x)))

In [69]:
emo

       shortcode                                               text  Emojis
0    B0nROchHqIs  petcare dogsofinstagram doglovers happy pet go...      []
1    B05jMzgHoZ0  dogsofchennai chennaidogs therapydogs touchmen...      []
6    B5KIVpbnDtg                                               Nice      []
12   B6FyPLUn3DS               The cat will always be sleeping mode      []
13   B6SNkllHCMI  Thank you sanchuanimalhospital for deworming t...  [😊, 🙏]
..           ...                                                ...     ...
235  CNSN-BbDFAj                                              Price      []
236  CNSN-BbDFAj                                                  😍     [😍]
237  CNSN-BbDFAj                                              Price      []
238  CNhqhtTjD-m                                                 Pp      []
239  CNr_1Kjj6Rm                                  Pp for one kg sis      []

[5078 rows x 3 columns]

In [70]:
emo = emo.explode('Emojis')
emo = emo.dropna(subset = ['Emojis'])

In [75]:
emo['image_url'] = ['https://www.instagram.com/p/{}/media/?size=l'.format(x) for x in emo['shortcode']]
emo

,shortcode,text,Emojis,image_url
13,B6SNkllHCMI,Thank you sanchuanimalhospital for deworming t...,😊,https://www.instagram.com/p/B6SNkllHCMI/media/...
13,B6SNkllHCMI,Thank you sanchuanimalhospital for deworming t...,🙏,https://www.instagram.com/p/B6SNkllHCMI/media/...
17,B67TS-Lnu8a,Thats my dog❤️❤️ Princess,❤️,https://www.instagram.com/p/B67TS-Lnu8a/media/...
20,B7RAM_mHlOc,pranalisuresh 😛,😛,https://www.instagram.com/p/B7RAM_mHlOc/media/...
23,B7cvpXxHdyZ,❤️,❤️,https://www.instagram.com/p/B7cvpXxHdyZ/media/...
...,...,...,...,...
230,CM7FR0ED32v,😍😍,😍,https://www.instagram.com/p/CM7FR0ED32v/media/...
232,CNJhoggjhUb,Very creative 👏❤️,👏,https://www.instagram.com/p/CNJhoggjhUb/media/...
232,CNJhoggjhUb,Very creative 👏❤️,❤️,https://www.instagram.com/p/CNJhoggjhUb/media/...
233,CNKivCYjPLb,Design super❤️,❤️,https://www.instagram.com/p/CNKivCYjPLb/media/...
236,CNSN-BbDFAj,😍,😍,https://www.instagram.com/p/CNSN-BbDFAj/media/...

In [76]:
emo.to_excel("instagram_emojis_extraction.xlsx")

In [13]:
sen = pro.copy()

In [14]:
sen

       shortcode                                               text
0    B0nROchHqIs  petcare dogsofinstagram doglovers happy pet go...
1    B05jMzgHoZ0  dogsofchennai chennaidogs therapydogs touchmen...
6    B5KIVpbnDtg                                               Nice
12   B6FyPLUn3DS               The cat will always be sleeping mode
13   B6SNkllHCMI  Thank you sanchuanimalhospital for deworming t...
..           ...                                                ...
235  CNSN-BbDFAj                                              Price
236  CNSN-BbDFAj                                                  😍
237  CNSN-BbDFAj                                              Price
238  CNhqhtTjD-m                                                 Pp
239  CNr_1Kjj6Rm                                  Pp for one kg sis

[25147 rows x 2 columns]

In [15]:
from transformers import pipeline
classifier = pipeline('sentiment-analysis')
def sentimentprocessing(text):
    try:
        return classifier(text)
    except Exception as e:
        print(e)
        return text

import swifter
sen['Sentiment_Analysis'] = sen.text.swifter.apply(lambda x:sentimentprocessing(x))
sen['Sentiment_Score'] = sen['Sentiment_Analysis'].apply(lambda x:x[0]['score'])
sen['Sentiment'] = sen['Sentiment_Analysis'].apply(lambda x:x[0]['label'])

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)
All model checkpoint layers were used when initializing TFDistilBertForSequenceClassification.

All the layers of TFDistilBertForSequenceClassification were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.
c:\users\hepl-it\appdata\local\programs\python\python38\lib\site-packages\swifter\swifter.py:36: UserWarning: This pandas object has duplicate indices, and swifter may not be able to improve performance. Consider resetting the indices with `df.reset_index(drop=True)`.
  warnings.warn(

Pandas Apply:   0%|          | 0/25147 [00:00<?, ?it/s]

In [16]:
sen

,shortcode,text,Sentiment_Analysis,Sentiment_Score,Sentiment
0,B0nROchHqIs,petcare dogsofinstagram doglovers happy pet go...,"[{'label': 'NEGATIVE', 'score': 0.877827644348...",0.877828,NEGATIVE
1,B05jMzgHoZ0,dogsofchennai chennaidogs therapydogs touchmen...,"[{'label': 'NEGATIVE', 'score': 0.976432502269...",0.976433,NEGATIVE
6,B5KIVpbnDtg,Nice,"[{'label': 'POSITIVE', 'score': 0.999855279922...",0.999855,POSITIVE
12,B6FyPLUn3DS,The cat will always be sleeping mode,"[{'label': 'NEGATIVE', 'score': 0.953148007392...",0.953148,NEGATIVE
13,B6SNkllHCMI,Thank you sanchuanimalhospital for deworming t...,"[{'label': 'POSITIVE', 'score': 0.919098258018...",0.919098,POSITIVE
...,...,...,...,...,...
235,CNSN-BbDFAj,Price,"[{'label': 'POSITIVE', 'score': 0.994482755661...",0.994483,POSITIVE
236,CNSN-BbDFAj,😍,"[{'label': 'NEGATIVE', 'score': 0.697056174278...",0.697056,NEGATIVE
237,CNSN-BbDFAj,Price,"[{'label': 'POSITIVE', 'score': 0.994482755661...",0.994483,POSITIVE
238,CNhqhtTjD-m,Pp,"[{'label': 'POSITIVE', 'score': 0.983071744441...",0.983072,POSITIVE
239,CNr_1Kjj6Rm,Pp for one kg sis,"[{'label': 'NEGATIVE', 'score': 0.956541538238...",0.956542,NEGATIVE

In [17]:
sen['image_url'] = ['https://www.instagram.com/p/{}/media/?size=l'.format(x) for x in sen['shortcode']]

In [18]:
sen

,shortcode,text,Sentiment_Analysis,Sentiment_Score,Sentiment,image_url
0,B0nROchHqIs,petcare dogsofinstagram doglovers happy pet go...,"[{'label': 'NEGATIVE', 'score': 0.877827644348...",0.877828,NEGATIVE,https://www.instagram.com/p/B0nROchHqIs/media/...
1,B05jMzgHoZ0,dogsofchennai chennaidogs therapydogs touchmen...,"[{'label': 'NEGATIVE', 'score': 0.976432502269...",0.976433,NEGATIVE,https://www.instagram.com/p/B05jMzgHoZ0/media/...
6,B5KIVpbnDtg,Nice,"[{'label': 'POSITIVE', 'score': 0.999855279922...",0.999855,POSITIVE,https://www.instagram.com/p/B5KIVpbnDtg/media/...
12,B6FyPLUn3DS,The cat will always be sleeping mode,"[{'label': 'NEGATIVE', 'score': 0.953148007392...",0.953148,NEGATIVE,https://www.instagram.com/p/B6FyPLUn3DS/media/...
13,B6SNkllHCMI,Thank you sanchuanimalhospital for deworming t...,"[{'label': 'POSITIVE', 'score': 0.919098258018...",0.919098,POSITIVE,https://www.instagram.com/p/B6SNkllHCMI/media/...
...,...,...,...,...,...,...
235,CNSN-BbDFAj,Price,"[{'label': 'POSITIVE', 'score': 0.994482755661...",0.994483,POSITIVE,https://www.instagram.com/p/CNSN-BbDFAj/media/...
236,CNSN-BbDFAj,😍,"[{'label': 'NEGATIVE', 'score': 0.697056174278...",0.697056,NEGATIVE,https://www.instagram.com/p/CNSN-BbDFAj/media/...
237,CNSN-BbDFAj,Price,"[{'label': 'POSITIVE', 'score': 0.994482755661...",0.994483,POSITIVE,https://www.instagram.com/p/CNSN-BbDFAj/media/...
238,CNhqhtTjD-m,Pp,"[{'label': 'POSITIVE', 'score': 0.983071744441...",0.983072,POSITIVE,https://www.instagram.com/p/CNhqhtTjD-m/media/...
239,CNr_1Kjj6Rm,Pp for one kg sis,"[{'label': 'NEGATIVE', 'score': 0.956541538238...",0.956542,NEGATIVE,https://www.instagram.com/p/CNr_1Kjj6Rm/media/...

In [19]:
sen.to_excel("sentiment.xlsx")

In [1]:
import pandas as pd
df = pd.read_excel("sentiment.xlsx")